server:
  port: 8001

#配置数据源
spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-2zegr75tx5c7v668xto.mysql.rds.aliyuncs.com:3306/pay?serverTimezone=GMT&amp&userSSL=false
    username:
    password:

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为ture。单节点无所谓，集群必须设置为true才能配合ribbon使用均衡负载
    fetch-registry: true
    service-url:
      #defaultZone: http://localhost:7001/eureka   #单机版
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka   #集群版


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.ali.springcloud.entities